-- ============================================================================
-- 0020 — record_transfer()  (ADR-035 §2.6, §2.4, §2.3, §1)
-- ============================================================================
-- docs/PLAN.md task 4e-i, the first half of 4e. The fourth of build step 4's
-- six write-surface functions, and the only one that touches two stores.
--
-- §2.6: `record_transfer(id, from_location, to_location, lines)` —
--   "Negative movements at origin, new batches at destination carrying cost
--    and expiry (§2.4). Screen deferred; shape fixed in 0004."
--
-- ⚠️ THE SCREEN IS DEFERRED AND THE FUNCTION IS NOT. §2.6's own note says the
-- UI waits for the second store; the write path is step 4's because
-- `void_transaction`, the failure path and every §2.10 row are written against
-- a write surface that is complete.
--
-- ----------------------------------------------------------------------------
-- ⚠️⚠️ WHAT MAKES THIS FUNCTION DIFFERENT: THERE IS NO DOCUMENT
-- ----------------------------------------------------------------------------
-- `record_sale`, `record_purchase` and `record_waste` each write a header and a
-- line table. A transfer writes NEITHER. §2.4 fixed the shape in `0004` and
-- `stock_movement.transfer_group_id` carries the comment that says so:
--
--   "A transfer has no document table — it is a pair of movements (§2.4). This
--    is what pairs them: one id, generated by the caller, on both the negative
--    movements at the origin and the positive ones at the destination."
--
-- That single fact is where every difference in this file comes from, and there
-- are four of them:
--
--   1. NO MONEY AT ALL. No net, no tax, no rate, no price. Stock moving between
--      two of the merchant's own stores is not a transaction with anybody —
--      §2.5 has nothing to say about it, and this is the only function on the
--      write surface with no tax split.
--   2. THE IDEMPOTENCY HASH IS RECOMPUTED, NOT STORED. There is no header to
--      put `payload_hash` on. See the section below.
--   3. THE RE-SEND RACE NEEDS AN EXPLICIT LOCK. There is no primary key to
--      collide on, so `on conflict (id) do nothing` — the mechanism §2.6's
--      third idempotency row relies on in the other three — does not exist
--      here. See the section below.
--   4. TWO LOCATION WALLS, NOT ONE, and a comparison rather than a derivation.
--
-- ----------------------------------------------------------------------------
-- ⚠️⚠️ THE LOCATION WALL IS DOUBLED, AND THE WORKSPACE IS COMPARED
-- ----------------------------------------------------------------------------
-- §2.6: "Where a transaction spans locations — only `record_transfer` — BOTH
-- are checked, and both must resolve to the same workspace."
--
-- 4b-i settled that the workspace is DERIVED from the location and never a
-- parameter, and named this function in advance as the one that cannot do it:
-- two locations are two workspaces until something proves otherwise, so the
-- derivation becomes a comparison. Both halves are here:
--
--   * ACCESS — each location is in `public.my_locations()`. A manager assigned
--     to Centro cannot ship stock out of Mercado, and cannot ship it in either.
--   * TENANCY — the two locations resolve to ONE workspace row.
--
-- ⚠️ `allocate_transfer()` ALREADY CHECKS THE TENANCY HALF (0005/0010) and this
-- file checks it again anyway. That is not redundant. The allocator's copy
-- exists so a composite FK does not fail halfway through its loop; this one
-- exists so the caller is refused BEFORE anything is written, with `42501` and
-- a message about access rather than a message about the ledger. The ACCESS
-- half has no copy anywhere — it is this function's alone, and `security
-- definer` means RLS is not running to catch its absence.
--
-- ----------------------------------------------------------------------------
-- ⚠️⚠️ IDEMPOTENCY WITH NOWHERE TO STORE IT — RECOMPUTED FROM THE LEDGER
-- ----------------------------------------------------------------------------
-- Decided in sizing 4e, on the owner's behalf, and recorded in docs/PLAN.md
-- under *Decided in sizing 4e*.
--
-- The other three RPCs store `payload_hash` on the header and compare it, and
-- that comparison is what turns §2.6's "same id, different lines" into `TD001`
-- rather than a duplicate-key error. There is no header here. Three answers
-- were available and the second was taken:
--
--   1. Add a column — a `transfer` header, or a hash on the movement. REFUSED:
--      §2.4 says a transfer has no document table DELIBERATELY, and `0004` says
--      so at the column. That is an ADR question, not a migration, and this
--      task has no mandate to ask it.
--   2. ✅ RECOMPUTE the hash from the `transfer_out` movements already written
--      under this `transfer_group_id`, and compare. No schema change, and the
--      contract survives intact.
--   3. Match on the id alone and return `already_recorded` with the lines
--      uncompared. Cheapest. REFUSED: it cannot raise `TD001`, which would make
--      this the one RPC in the write surface whose idempotency contract is
--      weaker than the other three's — discoverable only by a client that sends
--      a CORRECTED retry and is told its first, wrong version already succeeded.
--
-- 4d-i's rule is what forces it: "TD001 is REUSED, not re-invented — one
-- sqlstate for §2.6's same id, different payload across the whole write
-- surface." A function that cannot raise it has not inherited it.
--
-- ⚠️⚠️ AND THE RECOMPUTATION IS WHY ONE VARIANT MAY APPEAR ONLY ONCE PER
-- TRANSFER. The ledger records movements per LOT, not per line, so two payload
-- lines for the same variant are indistinguishable on the way back: `[A 2, A 3]`
-- and `[A 5]` leave the same five movements behind and would hash the same.
-- Rather than let the hash quietly become an approximation, the payload refuses
-- the duplicate up front with `22023` and a message that says to merge the two
-- lines. `record_sale` permits the same variant twice because `sale_line` keeps
-- the rows apart; nothing keeps them apart here.
--
-- ----------------------------------------------------------------------------
-- ⚠️⚠️ THE ADVISORY LOCK, AND WHY THE OTHER THREE DO NOT NEED ONE
-- ----------------------------------------------------------------------------
-- §2.6's four idempotency rows include: "first attempt still in flight → the
-- second call BLOCKS on the row lock". In `record_sale` that row lock is free —
-- `insert ... on conflict (id) do nothing` on a primary key, and the second
-- session waits on the uncommitted tuple. `supabase/vitest/test/idempotency.test.ts`
-- (task 3.7a) proves it on all three document tables.
--
-- ⚠️ THERE IS NO SUCH KEY HERE. `transfer_group_id` is a plain column with no
-- unique constraint — it CANNOT have one, because one shipment writes many rows
-- under one id, which is the whole point of it. So two concurrent calls with the
-- same id would both find no movements, both proceed, and write the shipment
-- TWICE: double the stock at the destination and a double withdrawal at the
-- origin, with nothing in the schema to refuse either.
--
-- The transaction-scoped advisory lock below closes that, and it is taken on the
-- id BEFORE the ledger is read. The second caller blocks there, and by the time
-- it proceeds the first has committed and its movements are visible — so it
-- takes the `already_recorded` path and returns the same summary. That is
-- §2.6's third row, restored by the only means available to a function with no
-- key to collide on.
--
-- ⚠️ IT IS NOT PROVED HERE, and this file does not claim it is. One session
-- cannot block on its own lock — 4c-i's F6 finding, in a second language. The
-- evidence is `supabase/vitest/`, and it is owed: see docs/PLAN.md.
--
-- A hash collision on `hashtextextended` would serialise two UNRELATED transfers
-- for the length of one transaction and change no outcome. That is the entire
-- downside, and it is why an advisory lock is acceptable where a fabricated
-- unique index would not be.
--
-- ----------------------------------------------------------------------------
-- ⚠️⚠️ THE AVAILABILITY CHECK — BUILT, DORMANT, AND SETTLED BY THE OWNER
-- ----------------------------------------------------------------------------
-- 4c-i left open whether §2.6's enforcement path applies to functions that are
-- not sales. The owner settled `record_waste` on 2026-09-04 — NO check, waste
-- records unconditionally — and settled THIS function on the same day, the
-- other way:
--
--   `record_transfer` GETS THE CHECK, BUILT AND DORMANT, THE SALE'S SHAPE.
--
-- The two answers differ because the failures differ, and the reasoning is
-- recorded because the code cannot carry it:
--
--   A write-off's debt STAYS IN ONE STORE. It shows up as a negative
--   `batch_balance` at the shop that lost the stock, where the shopkeeper can
--   see it and count against it.
--
--   AN UNBACKED TRANSFER INVENTS A LOT AT THE DESTINATION. `allocate_transfer()`
--   opens a `stock_batch` at store B carrying the cost and expiry of an origin
--   lot that was overdrawn to produce it — so the fiction does not stay put. It
--   crosses into a second store's shelf, takes a place in that store's FEFO
--   order by an expiry date it inherited from stock that was not there, and is
--   then sold or written off as though it were real. That is a materially worse
--   failure than waste's, and it is precisely the one a shopkeeper who has
--   turned enforcement ON is asking to be refused.
--
-- ⚠️ DORMANT IS THE DEFAULT AND IT IS THE SCHEMA'S, exactly as in `0017`.
-- `workspace_setting.enforce_stock_default` is `false` (0001) and
-- `product_variant.enforce_stock` is null everywhere in the seed, so this block
-- resolves to false for every caller that exists today and `0020` changes
-- nothing observable until a shopkeeper opts in. An unenforced transfer out of
-- an empty shelf still RECORDS, overdrawing the origin lot or opening an
-- `adjustment` one — §1, stock is recorded, not enforced.
--
-- The block is `0017`'s, re-spelled rather than shared for the reason `0018`
-- gives: plpgsql has no mixin, and a helper holding it would put the decision on
-- the far side of the wall §2.6 names. It resolves against the ORIGIN location,
-- which is the only one that can be short.
--
-- ----------------------------------------------------------------------------
-- ⚠️ THE OFFLINE SKIP, AND `occurred_at` STAMPS A LOT
-- ----------------------------------------------------------------------------
-- An offline transfer skips enforcement, for §2.6's reason on the sale: the van
-- has already left, and refusing it on reconnect discards a movement of stock
-- that physically happened.
--
-- ⚠️⚠️ AND `p_occurred_at` IS LOAD-BEARING IN A WAY IT IS NOWHERE ELSE, which is
-- the finding 4d-ii recorded and named this file in advance for. It is stamped
-- on `received_at` of EVERY destination lot (`0010`), not merely on the
-- movements — and `received_at` is FEFO's tiebreak (§2.4). A backdated transfer
-- therefore lands lots at store B dated when the van actually ran, in front of
-- stock that arrived after it. Passing `now()` here would put every late-flushed
-- shipment at the BACK of the destination's queue and quietly rotate that store
-- wrong. `supabase/tests/0020` section 7 is that made falsifiable.
--
-- ----------------------------------------------------------------------------
-- THE LINE PAYLOAD
-- ----------------------------------------------------------------------------
--   [{ "variant_id":       "<uuid>",
--      "qty_display":      <numeric>,
--      "qty_display_unit": "<unit code>" }]   -- optional; defaults to the
--                                             -- variant's SELL unit
--
-- ⚠️ THE DEFAULT UNIT IS `sell_unit_code`, AND THIS IS THE ONE CALL IN THE FILE
-- THE DIRECTION RULE DOES NOT DECIDE. 4d-ii's rule is "the DIRECTION of the
-- document, not the table" — `record_purchase` reads `purchase_unit_code`
-- because a delivery arrives, `record_waste` reads `sell_unit_code` because
-- stock leaves. A transfer does BOTH, so the rule is silent.
--
-- `sell_unit_code` is taken because the quantity is measured, allocated and
-- locked at the ORIGIN, where stock is leaving, and because the destination
-- lots are cut from what the origin gave up. ⚠️ It is one `coalesce` either way,
-- nothing in the seed depends on it, and it is flagged in docs/PLAN.md as the
-- cheap-now-dear-later call of this task: the moment a client sends a transfer
-- with no explicit unit, changing this re-scales quantities silently. That is
-- 4d-i's F3b shape and it applies clean.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- record_transfer()
-- ----------------------------------------------------------------------------

create function public.record_transfer(
  p_id                 uuid,
  p_from_location_id   uuid,
  p_to_location_id     uuid,
  p_lines              jsonb,
  p_occurred_at        timestamptz default null,
  p_recorded_offline   boolean     default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user      uuid := auth.uid();
  v_ws        uuid;
  v_ws_to     uuid;
  v_offline   boolean := coalesce(p_recorded_offline, false);
  v_now       timestamptz := now();
  v_at        timestamptz;
  v_problem   text;
  v_lines     jsonb;
  v_n         integer;
  v_hash      text;
  v_seen_hash text;
  v_seen_n    integer;
  v_seen_from uuid;
  v_seen_to   uuid;
  v_seen_ws   uuid;
  v_seen_at   timestamptz;
  v_from_n    integer;
  v_to_n      integer;
  v_ws_n      integer;
  v_out_lots  integer;
  v_line      record;
  v_enforce   boolean;
  v_vname     text;
  v_avail     numeric;
  v_legs      integer;
  v_lots      integer := 0;
begin
  -- ---- 1. the location wall, FIRST, and it is DOUBLED  (§2.6) -------------
  -- §2.6's four lines, spelled twice because this transaction spans two stores
  -- and §2.6 says both are checked. The origin is named first so a caller who
  -- holds neither is told about the one they were shipping FROM.
  if p_from_location_id is null
     or p_from_location_id not in (select public.my_locations()) then
    raise exception 'location not accessible'
      using errcode = '42501',
            detail  = 'The origin location is not one this caller is assigned to '
                      '(ADR-035 §2.6).';
  end if;

  if p_to_location_id is null
     or p_to_location_id not in (select public.my_locations()) then
    raise exception 'location not accessible'
      using errcode = '42501',
            detail  = 'The destination location is not one this caller is '
                      'assigned to (ADR-035 §2.6).';
  end if;

  if v_user is null then
    raise exception 'record_transfer requires an authenticated caller'
      using errcode = 'insufficient_privilege';
  end if;

  -- ⚠️ A COMPARISON, NOT A DERIVATION — 4b-i named this function as the one
  -- that cannot derive. Two locations the caller holds may still belong to two
  -- workspaces if this caller is a member of both, and a transfer between them
  -- would move stock across a tenant boundary with every access check passed.
  select l.workspace_id into v_ws
    from public.location l where l.id = p_from_location_id;
  select l.workspace_id into v_ws_to
    from public.location l where l.id = p_to_location_id;

  if v_ws is null or v_ws_to is null or v_ws <> v_ws_to then
    raise exception 'record_transfer: the origin and the destination are in '
                    'different workspaces — stock does not cross a tenant '
                    'boundary (ADR-035 §2.3, §2.6)'
      using errcode = '42501';
  end if;

  -- The allocator refuses this too (0005), with a message about allocation. It
  -- is here as well so the caller hears about the shipment they described
  -- rather than about a ledger primitive they never called.
  if p_from_location_id = p_to_location_id then
    raise exception 'record_transfer: the origin and the destination are the '
                    'same location — a transfer to itself would write a matched '
                    'pair against two lots at one store and invent a batch'
      using errcode = '22023';
  end if;

  -- ---- 2. the timestamps  (§2.6) ------------------------------------------
  -- ⚠️ This is the value that stamps `received_at` on every destination lot
  -- (0010), so it sets that store's FEFO tiebreak and not merely a report
  -- bucket. The clamp is 0016's, unchanged.
  if v_offline then
    v_at := greatest(least(coalesce(p_occurred_at, v_now), v_now),
                     v_now - interval '72 hours');
  else
    v_at := v_now;
  end if;

  -- ---- 3. the payload -----------------------------------------------------
  if p_id is null then
    raise exception 'record_transfer: the client must generate the transfer id '
                    '— it is the idempotency key and the transfer_group_id that '
                    'pairs the legs (ADR-035 §2.6, §2.4)'
      using errcode = '22023';
  end if;

  if p_lines is null or jsonb_typeof(p_lines) <> 'array'
     or jsonb_array_length(p_lines) = 0 then
    raise exception 'record_transfer: lines must be a non-empty json array, got %',
                    coalesce(jsonb_typeof(p_lines), 'null')
      using errcode = '22023';
  end if;

  -- VALIDATE EVERY LINE BEFORE MOVING ANY STOCK, AND NAME THE LINE — 0016's
  -- finding, inherited. An inner join with nothing in front of it DROPS an
  -- unresolvable line, and here that would ship a van the ledger only half
  -- knows about: stock missing at the origin with no record of where it went.
  select format('record_transfer: line %s — %s', v.ord, v.problem)
    into v_problem
    from (
      select e.ord,
             case
               when nullif(e.l->>'variant_id', '') is null
                 then 'variant_id is required'
               when nullif(e.l->>'qty_display', '') is null
                 then 'qty_display is required'
               when pv.id is null
                 then format('variant %s is not in this workspace',
                             e.l->>'variant_id')
               when u.code is null
                 then format('unit %L is not in the unit table',
                             coalesce(nullif(e.l->>'qty_display_unit', ''),
                                      pv.sell_unit_code))
               when u.base_code <> pv.base_unit_code
                 then format('unit %L is measured in %L, but the variant is '
                             'stored in %L — a conversion across dimensions has '
                             'no answer to give (ADR-035 §2.5)',
                             u.code, u.base_code, pv.base_unit_code)
               -- A negative leg is a transfer the other way. It is not spelled
               -- as a sign here, because the pair of movements is generated from
               -- the direction of the ARGUMENTS: swap the two locations.
               when (e.l->>'qty_display')::numeric <= 0
                 then format('quantity must be positive, got %s — a transfer '
                             'back is a transfer with the two locations '
                             'swapped, not a negative line',
                             e.l->>'qty_display')
               when round((e.l->>'qty_display')::numeric * u.factor_to_base, 3) <= 0
                 then format('qty_display %s %s rounds to zero in %L',
                             e.l->>'qty_display', u.code, pv.base_unit_code)
               -- ⚠️ THE DUPLICATE-VARIANT RULE, and it is this function's alone.
               -- The ledger keeps movements per LOT, so two lines for one
               -- variant are indistinguishable on the way back and the
               -- recomputed idempotency hash could not tell [A 2, A 3] from
               -- [A 5]. Refused rather than silently merged.
               when count(*) over (partition by nullif(e.l->>'variant_id', '')::uuid) > 1
                 then format('variant %s appears on more than one line — a '
                             'transfer has no line table (ADR-035 §2.4), so the '
                             'ledger cannot tell two lines apart afterwards. '
                             'Merge them into one line',
                             e.l->>'variant_id')
             end as problem
        from jsonb_array_elements(p_lines) with ordinality as e(l, ord)
        left join public.product_variant pv
          on pv.id = nullif(e.l->>'variant_id', '')::uuid
         and pv.workspace_id = v_ws
        left join public.unit u
          on u.code = coalesce(nullif(e.l->>'qty_display_unit', ''),
                               pv.sell_unit_code)
    ) v
   where v.problem is not null
   order by v.ord
   limit 1;

  if v_problem is not null then
    raise exception '%', v_problem using errcode = '22023';
  end if;

  -- ---- 4. the normalised lines  (§2.6) ------------------------------------
  -- 4b-i's rule: canonical base-unit quantities, taken AFTER unit conversion,
  -- ordered by content. `2` and `2.00` agree and `750 g` and `0.750 kg` agree.
  -- There is no money on a transfer, so the normalised line is the whole of it.
  select coalesce(jsonb_agg(to_jsonb(c) order by c.ord), '[]'::jsonb), count(*)
    into v_lines, v_n
    from (
      select e.ord,
             (e.l->>'variant_id')::uuid                     as variant_id,
             (e.l->>'qty_display')::numeric                 as qty_display,
             coalesce(nullif(e.l->>'qty_display_unit', ''),
                      pv.sell_unit_code)                    as qty_display_unit,
             round((e.l->>'qty_display')::numeric
                   * u.factor_to_base, 3)::numeric(14,3)    as qty_base
        from jsonb_array_elements(p_lines) with ordinality as e(l, ord)
        join public.product_variant pv
          on pv.id = (e.l->>'variant_id')::uuid
         and pv.workspace_id = v_ws
        join public.unit u
          on u.code = coalesce(nullif(e.l->>'qty_display_unit', ''),
                               pv.sell_unit_code)
    ) c;

  -- The anti-vacuity guard on the query above — 0016's shape, and it is not
  -- ceremony: the joins here are inner, and the pre-flight is the only thing
  -- standing between a dropped line and a half-shipped van.
  if v_n is distinct from jsonb_array_length(p_lines) then
    raise exception 'record_transfer: normalised % of % lines — the query '
                    'dropped one and the shipment would be recorded short',
                    coalesce(v_n, 0), jsonb_array_length(p_lines)
      using errcode = 'internal_error';
  end if;

  -- ⚠️ THE HASH IS OVER (variant, base quantity) AND MUST BE RECOMPUTABLE FROM
  -- THE LEDGER. Every term in it is one the `transfer_out` movements can give
  -- back; nothing that is not — the display unit, the ordinal, the moment — may
  -- enter, or a retry could never match. Section 5 recomputes it.
  select md5(string_agg(format('%s|%s', x.variant_id, x.qty_base),
                        E'\n' order by x.variant_id))
    into v_hash
    from jsonb_to_recordset(v_lines) as x(variant_id uuid, qty_base numeric(14,3));

  -- ---- 5. idempotency  (§2.6's four rows) ---------------------------------
  -- ⚠️ THE LOCK IS TAKEN BEFORE THE LEDGER IS READ, and it is what stands in for
  -- the primary-key conflict the other three RPCs get free. See the header.
  perform pg_advisory_xact_lock(hashtextextended(p_id::text, 0));

  -- THE RECOMPUTATION. Every term is one the ledger can give back: the variant
  -- and the base quantity, summed over the lots the allocator took. The
  -- `transfer_out` legs are the authority because they are what the origin
  -- actually gave up, and the payload is what the origin was asked for.
  select md5(string_agg(format('%s|%s', g.variant_id, g.qty_base),
                        E'\n' order by g.variant_id)),
         count(*)
    into v_seen_hash, v_seen_n
    from (
      select m.variant_id, sum(-m.qty_base)::numeric(14,3) as qty_base
        from public.stock_movement m
       where m.transfer_group_id = p_id
         and m.reason = 'transfer_out'
       group by m.variant_id
    ) g;

  -- The two stores and the moment, read off the legs themselves rather than off
  -- the grouped hash query. ⚠️ THE DISTINCT COUNTS ARE THE POINT: a group whose
  -- out-legs sit at more than one store is not a shipment this function ever
  -- wrote, and taking any single value from it would accept it as a retry of
  -- whichever row came back first.
  select count(distinct m.location_id), (array_agg(m.location_id))[1],
         count(distinct m.workspace_id), (array_agg(m.workspace_id))[1],
         min(m.occurred_at), count(*)
    into v_from_n, v_seen_from, v_ws_n, v_seen_ws, v_seen_at, v_out_lots
    from public.stock_movement m
   where m.transfer_group_id = p_id
     and m.reason = 'transfer_out';

  select count(distinct m.location_id), (array_agg(m.location_id))[1]
    into v_to_n, v_seen_to
    from public.stock_movement m
   where m.transfer_group_id = p_id
     and m.reason = 'transfer_in';

  if coalesce(v_seen_n, 0) > 0 then
    -- The same three comparisons `0016` makes, minus the one that has no home:
    -- the hash, the workspace and BOTH locations. A transfer id re-sent to a
    -- different pair of stores is not a retry, and returning the first
    -- shipment's summary for it would describe a van the caller never sent.
    if v_seen_hash    is distinct from v_hash
       or v_ws_n      is distinct from 1
       or v_from_n    is distinct from 1
       or v_to_n      is distinct from 1
       or v_seen_ws   is distinct from v_ws
       or v_seen_from is distinct from p_from_location_id
       or v_seen_to   is distinct from p_to_location_id then
      raise exception
        'transfer % was already recorded with a different payload', p_id
        using errcode = 'TD001',
              detail  = 'This is not a retry. Dead-letter it (ADR-035 §2.6).';
    end if;

    return jsonb_build_object(
      'transfer_id',       p_id,
      'workspace_id',      v_seen_ws,
      'from_location_id',  v_seen_from,
      'to_location_id',    v_seen_to,
      'occurred_at',       v_seen_at,
      -- ⚠️ NULL, AND IT IS NOT AN OVERSIGHT. `recorded_offline` is a column on
      -- the three document headers; a transfer has no header, so the ledger
      -- genuinely does not know whether the shipment it is reading back was
      -- filed from a queue. Returning `false` would be a claim this function
      -- cannot support, and the caller already knows what it sent.
      'recorded_offline',  null,
      'line_count',        v_seen_n,
      'lot_count',         v_out_lots,
      'already_recorded',  true
    );
  end if;

  -- ---- 6. the shipment  (§2.4) --------------------------------------------
  for v_line in
    select * from jsonb_to_recordset(v_lines)
      as x(ord              integer,
           variant_id       uuid,
           qty_display      numeric,
           qty_display_unit text,
           qty_base         numeric(14,3))
     order by x.ord
  loop
    -- ---- 6a. THE AVAILABILITY CHECK — BUILT, DORMANT  (§2.6) -------------
    -- 0017's block, re-spelled against the ORIGIN, which is the only location
    -- that can be short. Owner, 2026-09-04: this function gets the check where
    -- `record_waste` does not, because an unbacked transfer does not keep its
    -- debt in one store — it invents a lot at the destination. See the header.
    --
    -- Fail OPEN when the workspace has no settings row, deliberately and only
    -- here, exactly as 0017 argues.
    select coalesce(pv.enforce_stock, ws.enforce_stock_default, false), pv.name
      into v_enforce, v_vname
      from public.product_variant pv
      left join public.workspace_setting ws on ws.workspace_id = v_ws
     where pv.id = v_line.variant_id;

    if v_enforce and not v_offline then
      -- LOCK, then evaluate — and the predicate and the order are
      -- `allocate_fefo()`'s VERBATIM (0010), so this statement takes exactly
      -- the rows `allocate_transfer()` is about to take, one statement earlier.
      -- No new lock and NO NEW LOCK ORDERING: the destination side of a
      -- transfer takes none at all, because it only ever INSERTS fresh lots.
      with locked as (
        select bb.remaining_base
          from public.batch_balance bb
         where bb.workspace_id   = v_ws
           and bb.location_id    = p_from_location_id
           and bb.variant_id     = v_line.variant_id
           and bb.remaining_base > 0
         order by bb.expiry_date asc nulls last, bb.received_at asc,
                  bb.batch_id asc
         for update
      )
      select coalesce(sum(remaining_base), 0) into v_avail from locked;

      if v_avail < v_line.qty_base then
        raise exception
          'record_transfer: line % — % has % available at the origin and the '
          'shipment asks for %. Stock enforcement is on for this product '
          '(ADR-035 §2.6)',
          v_line.ord, coalesce(v_vname, v_line.variant_id::text),
          v_avail, v_line.qty_base
          using errcode = 'TD002';
      end if;
    end if;

    -- ⚠️ THE CALLER WRITES NOTHING HERE. `allocate_transfer()` does the entire
    -- paired write — the origin's FEFO withdrawal, one destination lot per
    -- origin lot carrying cost and expiry forward, and both movements under
    -- this `transfer_group_id` (0005, 0010). One destination lot per ORIGIN lot
    -- and not one per line: a shipment satisfied from three lots has three
    -- costs and three expiry dates, and one merged batch would lose both.
    --
    -- `p_id` IS the transfer_group_id. The client's idempotency key and the id
    -- that pairs the legs are the same value, because §2.4 gives a transfer no
    -- other identity to be known by.
    --
    -- `v_at` is passed, never `now()` — it stamps `received_at` on every lot
    -- this opens at the destination, which is that store's FEFO tiebreak.
    select count(*) into v_legs
      from public.allocate_transfer(v_ws, p_from_location_id, p_to_location_id,
                                    v_line.variant_id, v_line.qty_base,
                                    p_id, v_at, v_user) a;

    -- The allocator always returns at least one leg for a positive quantity —
    -- it overdraws or opens a lot rather than returning nothing (0010). Zero
    -- means the shipment recorded a line that moved no stock, which no
    -- constraint in the schema would notice.
    if coalesce(v_legs, 0) = 0 then
      raise exception 'record_transfer: the allocator returned no lots for '
                      'variant % — the line would be recorded as a shipment '
                      'that moved nothing', v_line.variant_id
        using errcode = 'internal_error';
    end if;

    v_lots := v_lots + v_legs;
  end loop;

  return jsonb_build_object(
    'transfer_id',      p_id,
    'workspace_id',     v_ws,
    'from_location_id', p_from_location_id,
    'to_location_id',   p_to_location_id,
    'occurred_at',      v_at,
    'recorded_offline', v_offline,
    'line_count',       v_n,
    'lot_count',        v_lots,
    'already_recorded', false
  );
end;
$$;

comment on function public.record_transfer(uuid, uuid, uuid, jsonb, timestamptz, boolean) is
  'Moves stock between two of a workspace''s own stores: FEFO-allocated negative '
  'movements at the origin and one new batch per origin lot at the destination, '
  'carrying cost and expiry forward, in one transaction. ⚠️ NO DOCUMENT — a '
  'transfer is a pair of movements (§2.4), so there is no money on it, its '
  'idempotency hash is RECOMPUTED from the transfer_out movements rather than '
  'stored, and a re-send race is held off by a transaction advisory lock '
  'instead of a primary key. Validates BOTH locations in its own body and '
  'compares them to ONE workspace — RLS is not running here. Availability check '
  'built and DORMANT, the sale''s shape, resolved against the origin (owner, '
  '2026-09-04): an unbacked transfer invents a lot at the destination, which a '
  'write-off never does. One variant per transfer. TD001 on a different payload '
  'under the same id, TD002 when enforcement is on and the origin is short. '
  'ADR-035 §1, §2.3, §2.4, §2.6.';


-- ----------------------------------------------------------------------------
-- Grants  (ADR-035 §2.7)
-- ----------------------------------------------------------------------------
-- `authenticated` and nothing else, and this function is the only route: 0005
-- grants EXECUTE on `allocate_transfer()` to no role at all, so the paired write
-- is unreachable except from inside a security definer body like this one.
--
-- ⚠️ THE GRANT DOES NOT ENCODE WHO MAY SHIP STOCK, and that is 4d-i's rule
-- applied again: this is a LOCATION wall, not a role test, and putting a role
-- test in the body would be a second spelling of an authorisation the RPC does
-- not own. §2.7's matrix has no transfer row yet — the screen is deferred — and
-- if shipping is to be role-gated it is a policy question, belonging where the
-- other forty policies are.

revoke all on function
  public.record_transfer(uuid, uuid, uuid, jsonb, timestamptz, boolean) from public;
grant execute on function
  public.record_transfer(uuid, uuid, uuid, jsonb, timestamptz, boolean) to authenticated;
