-- ============================================================================
-- GENERATED by supabase/catalog/build.mjs from supabase/catalog/*.csv.
-- ⚠️ DO NOT EDIT. Edit the CSVs and run `node supabase/catalog/build.mjs --write <label>`.
-- ============================================================================
-- A SNAPSHOT of the whole starter catalog (docs/PLAN.md Step 9, ADR-035 §2.9):
-- after this file `catalogo` holds exactly these rows. Upserted on `code`; a row
-- that left the CSVs leaves the template (shops keep their copies — nothing in
-- `public` references `catalogo`). `image_path` is never written here.
-- 11 tag(s), 2 family(ies), 24 product(s).

delete from catalogo.product_tag;
delete from catalogo.product where code not in ('pollo-entero', 'pechuga-entera', 'pechuga-deshuesada', 'milanesa-de-pollo', 'pierna', 'muslo', 'pierna-con-muslo', 'alitas', 'huacal', 'retazo', 'rabadilla', 'pescuezo', 'patas', 'molleja', 'higado', 'corazon', 'piel-de-pollo', 'pechuga-adobada', 'pechuga-empanizada', 'fajitas-de-pollo', 'nuggets-de-pollo', 'hamburguesa-de-pollo', 'huevo-blanco', 'huevo-rojo');

insert into catalogo.tag (code, kind, label, display_order) values
  ('giro-polleria', 'giro', 'Pollería', 1),
  ('giro-carniceria', 'giro', 'Carnicería', 2),
  ('giro-verduleria', 'giro', 'Verdulería', 3),
  ('giro-fruteria', 'giro', 'Frutería', 4),
  ('giro-abarrotes', 'giro', 'Abarrotes', 5),
  ('giro-cremeria', 'giro', 'Cremería', 6),
  ('giro-materias-primas', 'giro', 'Materias Primas', 7),
  ('cat-pollo-fresco', 'categoria', 'Pollo fresco', 8),
  ('cat-menudencia', 'categoria', 'Menudencia', 9),
  ('cat-preparados', 'categoria', 'Preparados', 10),
  ('cat-huevo', 'categoria', 'Huevo', 11)
on conflict (code) do update set kind = excluded.kind, label = excluded.label,
  display_order = excluded.display_order;

insert into catalogo.family (code, name, default_lifespan_days, track_expiry) values
  ('pollo', 'Pollo', null, false),
  ('huevo', 'Huevo', null, false)
on conflict (code) do update set name = excluded.name,
  default_lifespan_days = excluded.default_lifespan_days, track_expiry = excluded.track_expiry;

insert into catalogo.product (code, family_code, name, base_unit_code, purchase_unit_code,
       sell_unit_code, price_unit_code, pack_size, tax_rate, display_order) values
  ('pollo-entero', 'pollo', 'Pollo entero', 'g', 'kg', 'kg', 'kg', 1, 0, 1),
  ('pechuga-entera', 'pollo', 'Pechuga entera', 'g', 'kg', 'kg', 'kg', 1, 0, 2),
  ('pechuga-deshuesada', 'pollo', 'Pechuga deshuesada', 'g', 'kg', 'kg', 'kg', 1, 0, 3),
  ('milanesa-de-pollo', 'pollo', 'Milanesa de pollo', 'g', 'kg', 'kg', 'kg', 1, 0, 4),
  ('pierna', 'pollo', 'Pierna', 'g', 'kg', 'kg', 'kg', 1, 0, 5),
  ('muslo', 'pollo', 'Muslo', 'g', 'kg', 'kg', 'kg', 1, 0, 6),
  ('pierna-con-muslo', 'pollo', 'Pierna con muslo', 'g', 'kg', 'kg', 'kg', 1, 0, 7),
  ('alitas', 'pollo', 'Alitas', 'g', 'kg', 'kg', 'kg', 1, 0, 8),
  ('huacal', 'pollo', 'Huacal', 'g', 'kg', 'kg', 'kg', 1, 0, 9),
  ('retazo', 'pollo', 'Retazo', 'g', 'kg', 'kg', 'kg', 1, 0, 10),
  ('rabadilla', 'pollo', 'Rabadilla', 'g', 'kg', 'kg', 'kg', 1, 0, 11),
  ('pescuezo', 'pollo', 'Pescuezo', 'g', 'kg', 'kg', 'kg', 1, 0, 12),
  ('patas', 'pollo', 'Patas', 'g', 'kg', 'kg', 'kg', 1, 0, 13),
  ('molleja', 'pollo', 'Molleja', 'g', 'kg', 'kg', 'kg', 1, 0, 14),
  ('higado', 'pollo', 'Hígado', 'g', 'kg', 'kg', 'kg', 1, 0, 15),
  ('corazon', 'pollo', 'Corazón', 'g', 'kg', 'kg', 'kg', 1, 0, 16),
  ('piel-de-pollo', 'pollo', 'Piel de pollo', 'g', 'kg', 'kg', 'kg', 1, 0, 17),
  ('pechuga-adobada', 'pollo', 'Pechuga adobada', 'g', 'kg', 'kg', 'kg', 1, 0, 18),
  ('pechuga-empanizada', 'pollo', 'Pechuga empanizada', 'g', 'kg', 'kg', 'kg', 1, 0, 19),
  ('fajitas-de-pollo', 'pollo', 'Fajitas de pollo', 'g', 'kg', 'kg', 'kg', 1, 0, 20),
  ('nuggets-de-pollo', 'pollo', 'Nuggets de pollo', 'g', 'kg', 'kg', 'kg', 1, 0, 21),
  ('hamburguesa-de-pollo', 'pollo', 'Hamburguesa de pollo', 'g', 'kg', 'kg', 'kg', 1, 0, 22),
  ('huevo-blanco', 'huevo', 'Huevo blanco', 'g', 'kg', 'kg', 'kg', 1, 0, 23),
  ('huevo-rojo', 'huevo', 'Huevo rojo', 'g', 'kg', 'kg', 'kg', 1, 0, 24)
on conflict (code) do update set family_code = excluded.family_code, name = excluded.name,
  base_unit_code = excluded.base_unit_code, purchase_unit_code = excluded.purchase_unit_code,
  sell_unit_code = excluded.sell_unit_code, price_unit_code = excluded.price_unit_code,
  pack_size = excluded.pack_size, tax_rate = excluded.tax_rate, display_order = excluded.display_order;

delete from catalogo.family where code not in ('pollo', 'huevo');
delete from catalogo.tag where code not in ('giro-polleria', 'giro-carniceria', 'giro-verduleria', 'giro-fruteria', 'giro-abarrotes', 'giro-cremeria', 'giro-materias-primas', 'cat-pollo-fresco', 'cat-menudencia', 'cat-preparados', 'cat-huevo');

insert into catalogo.product_tag (product_code, tag_code) values
  ('pollo-entero', 'giro-polleria'),
  ('pollo-entero', 'cat-pollo-fresco'),
  ('pechuga-entera', 'giro-polleria'),
  ('pechuga-entera', 'cat-pollo-fresco'),
  ('pechuga-deshuesada', 'giro-polleria'),
  ('pechuga-deshuesada', 'cat-pollo-fresco'),
  ('milanesa-de-pollo', 'giro-polleria'),
  ('milanesa-de-pollo', 'cat-pollo-fresco'),
  ('pierna', 'giro-polleria'),
  ('pierna', 'cat-pollo-fresco'),
  ('muslo', 'giro-polleria'),
  ('muslo', 'cat-pollo-fresco'),
  ('pierna-con-muslo', 'giro-polleria'),
  ('pierna-con-muslo', 'cat-pollo-fresco'),
  ('alitas', 'giro-polleria'),
  ('alitas', 'cat-pollo-fresco'),
  ('huacal', 'giro-polleria'),
  ('huacal', 'cat-pollo-fresco'),
  ('retazo', 'giro-polleria'),
  ('retazo', 'cat-pollo-fresco'),
  ('rabadilla', 'giro-polleria'),
  ('rabadilla', 'cat-pollo-fresco'),
  ('pescuezo', 'giro-polleria'),
  ('pescuezo', 'cat-menudencia'),
  ('patas', 'giro-polleria'),
  ('patas', 'cat-menudencia'),
  ('molleja', 'giro-polleria'),
  ('molleja', 'cat-menudencia'),
  ('higado', 'giro-polleria'),
  ('higado', 'cat-menudencia'),
  ('corazon', 'giro-polleria'),
  ('corazon', 'cat-menudencia'),
  ('piel-de-pollo', 'giro-polleria'),
  ('piel-de-pollo', 'cat-menudencia'),
  ('pechuga-adobada', 'giro-polleria'),
  ('pechuga-adobada', 'cat-preparados'),
  ('pechuga-empanizada', 'giro-polleria'),
  ('pechuga-empanizada', 'cat-preparados'),
  ('fajitas-de-pollo', 'giro-polleria'),
  ('fajitas-de-pollo', 'cat-preparados'),
  ('nuggets-de-pollo', 'giro-polleria'),
  ('nuggets-de-pollo', 'cat-preparados'),
  ('hamburguesa-de-pollo', 'giro-polleria'),
  ('hamburguesa-de-pollo', 'cat-preparados'),
  ('huevo-blanco', 'giro-polleria'),
  ('huevo-blanco', 'cat-huevo'),
  ('huevo-rojo', 'giro-polleria'),
  ('huevo-rojo', 'cat-huevo');

-- The snapshot says how many rows it wrote; a partial apply is a failed one.
do $$
begin
  if (select count(*) from catalogo.tag) <> 11
     or (select count(*) from catalogo.family) <> 2
     or (select count(*) from catalogo.product) <> 24
     or (select count(*) from catalogo.product_tag) <> 48 then
    raise exception 'starter catalog snapshot did not land whole'
      using errcode = 'check_violation';
  end if;
end;
$$;
